// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd7QxVoD_SNFToOTu8hTlhqv9Fbmrrqrk',
    appId: '1:648138473889:web:9293b7b73e31e2a4064be0',
    messagingSenderId: '648138473889',
    projectId: 'spendwise-naman',
    authDomain: 'spendwise-naman.firebaseapp.com',
    storageBucket: 'spendwise-naman.firebasestorage.app',
    measurementId: 'G-SCF4G2GHDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHKA8e00G0aP6wF00PHdlO4ePNmJ2bE6Y',
    appId: '1:648138473889:android:f5901401eaa4c2ff064be0',
    messagingSenderId: '648138473889',
    projectId: 'spendwise-naman',
    storageBucket: 'spendwise-naman.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyNq5BO9lt4Oy_D9Z391zM4wf--UiV2h0',
    appId: '1:648138473889:ios:6e4d438a4b6bc2a5064be0',
    messagingSenderId: '648138473889',
    projectId: 'spendwise-naman',
    storageBucket: 'spendwise-naman.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
      );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyNq5BO9lt4Oy_D9Z391zM4wf--UiV2h0',
    appId: '1:648138473889:ios:6e4d438a4b6bc2a5064be0',
    messagingSenderId: '648138473889',
    projectId: 'spendwise-naman',
    storageBucket: 'spendwise-naman.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd7QxVoD_SNFToOTu8hTlhqv9Fbmrrqrk',
    appId: '1:648138473889:web:00a4a7d73128cd5a064be0',
    messagingSenderId: '648138473889',
    projectId: 'spendwise-naman',
    authDomain: 'spendwise-naman.firebaseapp.com',
    storageBucket: 'spendwise-naman.firebasestorage.app',
    measurementId: 'G-W6HLS6MQLR',
  );
}
